<?xml version="1.0" encoding="utf-8"?>

<!DOCTYPE channel [
<!ELEMENT channel  (#PCDATA)>
<!ATTLIST channel id ID #REQUIRED>
<!ATTLIST channel code CDATA #REQUIRED>
<!ATTLIST channel url CDATA #REQUIRED>
<!ATTLIST channel file CDATA #REQUIRED>
<!ATTLIST channel catalog CDATA #REQUIRED>
]>
<channels>
<channel id ="001" code="SCTV1" url="rtmp://112.197.2.11:1935/live" file="sctv1.stream" catalog="SCTV"> </channel>
<channel id ="002" code="SCTV2" url="rtmp://112.197.2.11:1935/live" file="sctv2.stream" catalog="SCTV"> </channel>
<channel id ="003" code="SCTV3" url="rtmp://112.197.2.11:1935/live" file="sctv3.stream" catalog="SCTV"> </channel>
<channel id ="004" code="SCTV4" url="rtmp://112.197.2.11:1935/live" file="sctv4.stream" catalog="SCTV"> </channel>
<channel id ="005" code="SCTV5" url="rtmp://112.197.2.11:1935/live" file="sctv5.stream" catalog="SCTV"> </channel>
<channel id ="006" code="SCTV6" url="rtmp://112.197.2.11:1935/live" file="sctv6.stream" catalog="SCTV"> </channel>
<channel id ="007" code="SCTV7" url="rtmp://112.197.2.11:1935/live" file="sctv7.stream" catalog="SCTV"> </channel>
<channel id ="008" code="SCTV8" url="rtmp://112.197.2.11:1935/live" file="sctv8.stream" catalog="SCTV"> </channel>
<channel id ="009" code="SCTV9" url="rtmp://112.197.2.11:1935/live" file="sctv9.stream" catalog="SCTV"> </channel>
<channel id ="010" code="SCTV10" url="rtmp://112.197.2.11:1935/live" file="sctv10.stream" catalog="SCTV"> </channel>
<channel id ="011" code="SCTV12" url="rtmp://112.197.2.11:1935/live" file="sctv12.stream" catalog="SCTV"> </channel>
<channel id ="012" code="SCTV13" url="rtmp://112.197.2.11:1935/live" file="sctv13.stream" catalog="SCTV"> </channel>
<channel id ="013" code="SCTV14" url="rtmp://112.197.2.11:1935/live" file="sctv14.stream" catalog="SCTV"> </channel>
<channel id ="014" code="SCTV15" url="rtmp://112.197.2.11:1935/live" file="sctv15.stream" catalog="SCTV"> </channel>
<channel id ="015" code="SCTV16" url="rtmp://112.197.2.11:1935/live" file="sctv16.stream" catalog="SCTV"> </channel>
<channel id ="016" code="SCTV17" url="rtmp://112.197.2.11:1935/live" file="sctv17.stream" catalog="SCTV"> </channel>
<channel id ="017" code="SCTV18" url="rtmp://112.197.2.11:1935/live" file="sctv18.stream" catalog="SCTV"> </channel>


<channel id ="034" code="VTV1" url="rtmp://117.103.232.2/live" file="vtv11" catalog="VTV"> </channel>
<channel id ="018" code="VTV1" url="rtmp://66.160.142.197/live" file="vtv11" catalog="VTV"> </channel>
<channel id ="019" code="VTV2" url="rtmp://66.160.142.197/live" file="vtv2" catalog="VTV"> </channel>
<channel id ="020" code="VTV3" url="rtmp://66.160.142.197/live" file="vtv31" catalog="VTV"> </channel>
<channel id ="021" code="VTV4" url="rtmp://66.160.142.198/live" file="vtv4" catalog="VTV"> </channel>
<channel id ="035" code="VTV2" url="rtmp://117.103.225.4/live" file="vtv2" catalog="VTV"> </channel>
<channel id ="036" code="VTV3" url="rtmp://117.103.225.4/live" file="vtv31" catalog="VTV"> </channel>
<channel id ="037" code="VTV4" url="rtmp://117.103.232.4/live" file="vtv4" catalog="VTV"> </channel>

<channel id ="022" code="VTC1" url="rtmp://66.160.142.198/live" file="vtc11" catalog="VTC"> </channel>
<channel id ="046" code="VTC1" url="rtmp://117.103.225.16:1935/live" file="vtc11" catalog="VTC"> </channel>
<channel id ="023" code="VTC2" url="rtmp://66.160.142.197/live" file="vtc21" catalog="VTC"> </channel>
<channel id ="031" code="VTC1" url="rtmp://117.103.232.2/live" file="vtc11" catalog="VTC"> </channel>
<channel id ="032" code="VTC2" url="rtmp://117.103.232.2/live" file="vtc21" catalog="VTC"> </channel>
<channel id ="033" code="VTC10" url="rtmp://117.103.232.2/live" file="vtc101" catalog="VTC"> </channel>
<channel id ="024" code="VTC10" url="rtmp://66.160.142.198/live" file="vtc101" catalog="VTV"> </channel>

<channel id ="025" code="HANOI" url="rtmp://66.160.142.198/live" file="hanoi11" catalog="HTV"> </channel>
<channel id ="026" code="HTV7" url="rtmp://66.160.142.198/live" file="htv7" catalog="HTV"> </channel>
<channel id ="027" code="HTV9" url="rtmp://66.160.142.197/live" file="htv91" catalog="HTV"> </channel>
<channel id ="028" code="HTV7" url="rtmp://117.103.225.4/live" file="htv7" catalog="HTV"> </channel>
<channel id ="029" code="HTV9" url="rtmp://117.103.232.3/live" file="htv91" catalog="HTV"> </channel>
<channel id ="030" code="HN1" url="rtmp://117.103.225.16/live" file="hanoi11"  catalog="HTV"> </channel>

<channel id ="040" code="VOV1" url="rtmp://117.103.232.3/live" file="vov1" catalog="VOV"> </channel>
<channel id ="041" code="VOV2" url="rtmp://117.103.232.2/live" file="vov2" catalog="VOV"> </channel>
<channel id ="042" code="VOV3" url="rtmp://117.103.232.2/live" file="vov3" catalog="VOV"> </channel>
<channel id ="043" code="VOV4" url="rtmp://117.103.232.2/live" file="vov5" catalog="VOV"> </channel>
<channel id ="044" code="VOVGT" url="rtmp://123.30.50.46/live" file="vovgt" catalog="VOV">Giao thong Ha noi</channel>
<channel id ="045" code="VOVGT" url="rtmp://123.30.50.46:8080/live" file="vovgtsg" catalog="VOV">Giao thong Sai gon</channel>

<channel id ="038" code="THVP" url="rtmp://210.245.87.165/live" file="thvp">Vinh phuc</channel>
<channel id ="039" code="BRT" url="rtmp://117.103.225.2/live" file="brt">BA RIA</channel>

</channels>
